### ISSUE TITLE
Exercise 1: User Class Exercise

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#1]
Create a class User with name and age as its attribute.Instantiate two objects user1 and user2 with some value. Create a method compare that compares the age of user1 and user2. The method should be called in this way:user1.compare(user2)this method should return output like"joh n is older than mary" or "mary is older than john" based on their age comparision.

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-1

**Comment by segunadeleye** [comment]
1. You are to pass in a user object as parameter, not the age.
2. Account for when ages are equal.
3. Use ES6 string interpolation rather than string concatenation.
4. Add outputs for other possible results. Don't worry about adding the outputs to the DOM, you can simply log them to the console.
5. Let's account for age input of "025".
6. Use a better variable name instead of `caparison`.
7. Why are we passing an empty string to `text`, there is a better way to do this.

**Comment by ayodeleopetumo** [comment]
Made the corrections to exercise-1.js file to reflect the fixes to the issues raised.

**Comment by segunadeleye** [comment]
Looks good
