### ISSUE TITLE
Exercise 5: Dynamic Table addrows, edit and delete existing rows

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#12]
Create a table. When you click on 'Add new row' button: It should add a new row in the table. In the name and email column there will a textfield. In the action column there will be a button save. When you enter some value in textfields and click save, then:
1. Values will be saved(if valid). i.e. Name should be present, Email should be a valid email. 
2. Textfields will be replaced by the values entered. 
3. Save button will be replace by edit / delete links.
   You should be able to delete row by clicking on the delete link, and edit value by clicking on the edit link.

https://github.com/ayodeleDD/JS-Tracks/blob/master/Exercise-5/exercise-5.js

**Comment by segunadeleye** [comment]
On https://github.com/ayodeleDD/JS-Tracks/blob/master/Exercise-5/exercise-5.js#L25, since you have chosen to save the elements in an object, you can pass them into `saveTableRow()` and then access each input as required.

https://github.com/ayodeleDD/JS-Tracks/blob/master/Exercise-5/exercise-5.js#L46 I guess you mean `identifier` and not `name`. Or is it the other way round. However, whatever it is make the necessary correction

**Comment by ayodeleopetumo** [comment]
Made necessary improvements

**Comment by segunadeleye** [comment]
Looks good
