### ISSUE TITLE
Exercise 3: Maximum 3 checkbox selected

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#3]
Create a list of checkboxs(Sunday, Monday, Wednesday, Thursday, Tuesday, Friday, Saturday and none). Now when I start checking these checkboxs, it should not let me check more than 3 checkboxes. When I try to check on 4th checkbox it should alert me as "Only 3 days can be selected. You have already selected sunday, monday and tuesday". Now when I click on none, all other checkboxs should be deselected. Also when 'none' is selected and I select any other option(lets assume sunday), that option(sunday) will be selected and none will be deselected.

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-3

**Comment by segunadeleye** [comment]
1. Checkboxes cannot have the same name.
2. Uncheck the 4th checkboxes before displaying the alert message.
3. Use the right naming convention for the class name.
4. Don't use abbreviations for variable names. Use descriptive names for your variables, methods and classes. Replicate this in other exercises.
5. I don't think it is proper to use a `cursor: pointer` for your label.
6. You can make this app open-ended. So that it is possible to change the limit.
7. You can check for something else instead of `formElement.id`
8. `verifyMax()` is doing much more than just verification. You can create a method to handle other things.
9. You don't need to check for this `wkdayCB[i].id !== 'none'`.
10. You can move the logic for the form click event into a method.
11. You don't need to store the checked elements in an array. You can select them from the DOM.
    Let's discuss if you have any doubt.

**Comment by ayodeleopetumo** [comment]
Issues fixed

**Comment by segunadeleye** [comment]
1. Why are you passing `checkBoxLimit` as an argument if you can access it through `this.checkBoxLimit`.
2. Why this?: https://github.com/ayodeleDD/JS-Tracks/blob/master/Exercise-3/weekdays.js#L47
3. The none checkbox should only be unchecked if it is checked.
4. There is a much better way to select checked checkboxes instead of saving each one in checkBoxArray. Read about `querySelector()` and `querySelectorAll()`

**Comment by ayodeleopetumo** [comment]
Fixed Issues pointed out.

**Comment by ayodeleopetumo** [comment]
Made corrections to the JS file...

**Comment by segunadeleye** [comment]
Looks good. However, remove unused arguments from `verifyMax()`
