### ISSUE TITLE
Exercise 11: Matching numerical values and event propogation

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/JS-Tracks#7]
Create a form with two textfields labeled "Enter Number" and "Result". When I enter something in first textfield and submit the form, it should write true in second textfield if entered value is numeric otherwise false. Also if entered value is not numeric, form should not be submitted. Please use only Object oriented
approach to write your code.

https://github.com/ayodeleDD/JS-Tracks/tree/master/Exercise-11

**Comment by segunadeleye** [comment]
1. You should have a different method that handles the check for empty field and another one that handles the check for number.
2. Since you are using `submit()`, you should use a different event handler instead of `submit`
3. Instead of passing so many arguments into a method, is it not possible to declare them as variables within the method itself?

**Comment by ayodeleopetumo** [comment]
Issues fixed

**Comment by ayodeleopetumo** [comment]
Made corrections to the JS file...

**Comment by ayodeleopetumo** [comment]
Updated
